job_desc_path: "escoe_extension/outputs/data/model_application_data/"
job_sent_path: "sentence_chunks/"
chunk_size: 900
checkpoint: "distilbert-base-uncased"
bert_chunk_size: 128
wwm_probability: 0.2
mlm_probability: 0.15
bert_train_size: 100_000
bert_batch_size: 64
