training_data_path: "outputs/data/labelled_job_adverts/company_desc_sic_labelled_sentences.csv"
checkpoint: "jjzha/jobbert-base-cased"
model_name: "jobbert-base-cased-compdecs"
random_seed: 42
output_dir: "results"
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
num_train_epochs: 10
weight_decay: 0.01
